package net.sandikta.smp.aplikasi.entities.enums;

public enum NamaMataPelajaran {

	PENDIDIKAN_AGAMA,
	PENDIDIKAN_KEWARGANEGARAAN,
	BAHASA_INDONESIA,
	BAHASA_INGGRIS,
	MATEMATIKA,
	ILMU_PENGETAHUAN_ALAM,
	ILMU_PENGETAHUAN_SOSIAL,
	SENI_BUDAYA,
	PENDIDIKAN_OLAHRAGA_kESEHATAN,
	TEKNOLOGI_INFORMASI_KOMUNIKASI,
	BAHASA_SUNDA,
	PENDIDIKAN_LINGKUNGAN_HIDUP
}