package net.sandikta.smp.aplikasi.desktop;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.scene.control.Label;
import javafx.scene.control.ListCell;
import javafx.scene.control.ListView;
import javafx.util.Callback;
import net.sandikta.smp.aplikasi.entities.Siswa;
import net.sandikta.smp.aplikasi.entities.TahunPelajaran;

public class SelectSiswaController implements Initializable {
	
	Siswa siswa = new Siswa();
	
	private ObservableList<TahunPelajaran> tahunPelajaranObser = 
			FXCollections.observableArrayList();;
	
	@FXML
	private Label lblTahunPelajaranSiswa;
	@FXML
	private ListView<TahunPelajaran> listTahunPelajaranSiswa;
	@FXML
	private Button btnUpdateTahunPelajaranSiswa;
	@FXML
	private Button btnSaveTahunPelajaranSiswa;
	@FXML
	private Button btnHapusTahuPelajaranSiswa;
	
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		listTahunPelajaranSiswa.setItems(tahunPelajaranObser);
		listTahunPelajaranSiswa.setCellFactory(new Callback<ListView<TahunPelajaran>, 
				ListCell<TahunPelajaran>>() {
			@Override
			public ListCell<TahunPelajaran> call(ListView<TahunPelajaran> param) {
				return new TahunPelajaranListViewCell(siswa);
			}
		});
	}
	
	static class TahunPelajaranListViewCell extends ListCell<TahunPelajaran> {
		private Siswa siswa;
		public TahunPelajaranListViewCell(Siswa sis) {
			siswa = sis;
		}
		@Override
		protected void updateItem(TahunPelajaran tahunPelajaran, boolean empty) {
			super.updateItem(tahunPelajaran, empty);
			if (tahunPelajaran != null) {
				setText(siswa.getNama() + "\t\t" +tahunPelajaran.getKelas() + "\t\t" + 
						tahunPelajaran.getSemester() + "\t\t" + 
						tahunPelajaran.getIdTahunPelajaran());
			}
		}
	}

	public Siswa getSiswa() {
		return siswa;
	}

	public void setSiswa(Siswa sis) {
		this.siswa = sis;
		tahunPelajaranObser.addAll(siswa.getTahunPelajaran());
	}
	
	// Event Listener on Button[#btnUpdateTahunPelajaranSiswa].onAction
	@FXML
	public void updateTahunPelajaranSiswa(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSaveTahunPelajaranSiswa].onAction
	@FXML
	public void savePdfTahunPelajaranSiswa(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnHapusTahuPelajaranSiswa].onAction
	@FXML
	public void hapusTahunPelajaranSiswa(ActionEvent event) {
		// TODO Autogenerated
	}
}
